# Generated by Django 3.1.4 on 2020-12-31 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_img', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_uname', models.CharField(max_length=200)),
                ('c_comment', models.CharField(max_length=800)),
                ('c_reply', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_uname', models.CharField(max_length=200)),
                ('f_feedback', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_name', models.CharField(max_length=200)),
                ('g_desc', models.CharField(max_length=800)),
                ('g_img', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=200)),
                ('user_address', models.CharField(max_length=200)),
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=200)),
                ('p_desc', models.CharField(max_length=200)),
                ('p_price', models.IntegerField()),
                ('p_img', models.FileField(upload_to='media')),
                ('user_id', models.FileField(upload_to='media')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
